name: Flask Chatbot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # You can specify a Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Download SpaCy language model
    - name: Download SpaCy model
      run: |
        python -m spacy download en_core_web_sm

    # Step 5: Run tests (optional)
    - name: Run tests
      run: |
        python -m unittest discover  # Assuming you have tests in your project

    # Step 6: Start Flask app (optional, for deployment or testing)
    - name: Run Flask app
      run: python app.py
      env:
        FLASK_ENV: development
