name: Flask Chatbot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Step 3: List repository files for debugging
    - name: List files in the repository
      run: ls -R  # This will list all files and directories recursively

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Update if necessary

    # Step 5: Download SpaCy language model
    - name: Download SpaCy model
      run: |
        python -m spacy download en_core_web_sm

    # Step 6: Run tests (optional)
    - name: Run tests
      run: |
        python -m unittest discover

    # Step 7: Start Flask app (optional, for deployment or testing)
    - name: Run Flask app
      run: python app.py  # Adjust the path to match your project structure
      env:
        FLASK_ENV: development
