name: Flask Chatbot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify your desired Python version

    # Step 3: Create a virtual environment
    - name: Create virtual environment
      run: |
        python -m venv venv  # Create virtual environment
        source venv/bin/activate  # Activate the virtual environment
        echo "##[add-path]$(pwd)/venv/bin"  # Add virtual environment to PATH for future steps

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        source venv/bin/activate  # Activate the virtual environment
        python -m pip install --upgrade pip
        pip install -r flask_chatbot/requirements.txt  # Adjust path if necessary

    # Step 5: Download SpaCy language model
    - name: Download SpaCy model
      run: |
        source venv/bin/activate  # Activate the virtual environment
        python -m spacy download en_core_web_sm

    # Step 6: Run tests (optional)
    - name: Run tests
      run: |
        source venv/bin/activate  # Activate the virtual environment
        python -m unittest discover  # Assuming you have tests in your project

    # Step 7: Start Flask app (optional, for deployment or testing)
    - name: Run Flask app
      run: |
        source venv/bin/activate  # Activate the virtual environment
        python app.py
      env:
        FLASK_ENV: development
